<?xml
<definitions
  <types>
    <xsd:schema
      <xsd:element
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element
      <xsd:simpleType
        <xsd:restriction
          <xsd:length
          <xsd:pattern
      <xsd:simpleType
        <xsd:restriction
          <xsd:enumeration
      <xsd:complexType
        <xsd:sequence>
          <xsd:element
      <xsd:simpleType
        <xsd:restriction
          <xsd:enumeration
      <xsd:element
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element
      <xsd:complexType
        <xsd:sequence>
          <xsd:element
      <xsd:element
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element
  <message
    <part
  <portType
    <operation
      <input
      <output
  <binding
    <soap:binding
    <operation
      <soap:operation
      <input>
        <soap:header
        <soap:body
      <output>
        <soap:header
        <soap:body
  <service
    <documentation></documentation>
    <port
      <soap:address
